### ISSUE TITLE
Site updates

### ISSUE THREAD

**Issue by harshasrikara** [acmutd/acmutd.github.io#35]
# Bring site up to date

Fall 2020 revisions

**Task List**

 - [x] Remove old expired applications
 - [x] Add new dev applications
 - [x] Add all events for the fall semester
 - [x] Mark certain events as featured
 - [x] Add page for scholarship w description (this is the only one that requires writing html code)
 - [x] Add new officers, change positions/titles for existing officers, if they don't have a profile photo check in google drive for their images, if they joined the team after those photos were taken dm them asking for a photo or use the division logo instead
 - [x] Check google drive (ACM General Shared Drive) for information all the above points like who is an officer, their name, event lists, etc.

**Additional Notes**

Apart from the scholarship page, everything is pretty much just updating the readme files. Use `jekyll serve` to run the code locally. Jekyll will automatically parse the readme files and render to the page.

**Comment by jafrilli** [comment]
The officer database itself is not updated. I'm still marked as an Education officer. Also there is no option for development (for team)

**Comment by jafrilli** [comment]
besides that everything is done
